# -*- coding: utf-8 -*-
import io, re

SF='https://siliconflorist.com'
YT='https://youtube.com/@turoczy_'
SS='https://www.slideshare.net/turoczy'

GROUPS = [
("talk", "Keynotes, conference talks, and panels", [
 ("2018","Columbia GSAPP &mdash; &ldquo;Labs, Incubators, Colonies: Propeller and PIE,&rdquo; a duet with Andrea Chen of Propeller, New Orleans. Wood Auditorium, cohosted with NEW INC.","https://www.youtube.com/watch?v=_kDXQk9p314"),
 ("2018","TEDxPortland &mdash; &ldquo;An Introvert&rsquo;s Guide to Networking,&rdquo; Keller Auditorium, 3,000+ people","https://www.youtube.com/watch?v=Cj98mr_wUA0"),
 ("2013","HubSpot INBOUND, Boston &mdash; &ldquo;The Power of Humility,&rdquo; Bold Talks track","https://www.youtube.com/watch?v=Cs7Hr_CN5v4"),
 ("2020","Skoll World Forum &mdash; &ldquo;Ecosystem Builders as Second Responders to Crisis&rdquo;","https://socialventurers.com/ecosystem-builders-as-second-responders-to-crisis/"),
 ("2018","Kauffman Foundation ESHIP Summit, Kansas City &mdash; &ldquo;Why do you do what you do?&rdquo;","https://www.youtube.com/watch?v=VsnNX2vPJM8"),
 ("recurring","SXSW Interactive, Austin &mdash; SXSW Pitch judge and advisory board, and curator of the Portland Tech Meet Up",""),
 ("2013","PSU Elevating Impact Summit &mdash; moderator, &ldquo;Resilience: Uncensored&rdquo;","https://www.pdx.edu/business/elevating-impact-2013"),
 ("2024","Silicon Forest Tech Summit &mdash; introducing the inaugural summit","https://www.youtube.com/watch?v=i3uXRPMEcGs"),
 ("2015","Whitman College &mdash; Andjelkovic Endowed Lecture Series, back at the alma mater","https://www.youtube.com/watch?v=5eyIqdpG4ZU"),
 ("2015","New Relic FutureTalk &mdash; moderating &ldquo;Mobile Strategy for Today and Tomorrow&rdquo;","https://www.youtube.com/watch?v=6S7t-vYhWYk"),
 ("2012","SOBCon, Chicago &mdash; on building things people actually show up for","https://www.youtube.com/watch?v=s5e0sH3POlw"),
 ("2009","InnoTech Conference &mdash; &ldquo;To Blog Or Not to Blog&rdquo;","https://www.slideshare.net/slideshow/20090422innotechblogornot/1361308"),
 ("archival","OEN PubTalk, Portland &mdash; &ldquo;The Tech Startup Scene in Portland&rdquo;",""),
 ("2026","PubTalks Fireside Chat, Eugene &mdash; two decades of Oregon startups","https://www.tickettailor.com/events/collaborativeedo/2023310"),
 ("2025","FOSSY &mdash; &ldquo;Cooking Up Community: Build the Fire, Embrace Every Ingredient, Always Stir the Pot&rdquo;","https://2025.fossy.us/speaker/profile/486/index.html"),
 ("2008&ndash;09","PDX Web Innovators &mdash; Portland tech community retrospective and outlook","https://www.slideshare.net/slideshow/2008-portland-tech-recap-presentation/816775"),
 ("multiple","Kobe, Japan &mdash; invited keynote on regional ecosystem development",""),
 ("multiple","Muscat, Oman &mdash; invited keynote on building on local assets instead of cloning Silicon Valley",""),
]),
("show", "Shows I host", [
 ("2023&ndash;","<i>Portland, Oregon, Startup News</i> &mdash; weekly companion to Silicon Florist. Apple Podcasts, Spotify, Libsyn, YouTube","https://podcasts.apple.com/us/podcast/portland-oregon-startup-news-silicon-florist/id1711294699"),
 ("2024&ndash;","<i>Startup Stories with Silicon Florist</i> &mdash; long-form founder interviews across Oregon and SW Washington","https://podcasts.apple.com/us/podcast/startup-stories-with-silicon-florist/id1849468494"),
 ("2024&ndash;","<i>The Long Con</i> &mdash; in person only, no video calls, no format","https://podcasts.apple.com/us/podcast/the-long-con-with-rick-turoczy/id1810923457"),
 ("2023&ndash;","<i>Mildly Interesting People</i> &mdash; co-creator and co-host, with Cami Kaos","https://mildlyinterestingpeople.com/"),
 ("2020&ndash;21","<i>PIE Crowdcast</i> &mdash; live AMA series for founders during the pandemic","https://www.crowdcast.io/piepdx"),
 ("2009&ndash;11","<i>memePDX</i> &mdash; co-host with Cami Kaos. Episodes live in the Silicon Florist archive.","https://siliconflorist.com/2010/02/25/memepdx-026-jive-software-ceo-dawn-foster-joins-meego-open-source-bridge-yahoo-twitter-ngmoco-raises-25-million/"),
]),
("pod", "Podcasts and broadcasts, as a guest", [
 ("2023","<i>PDX Executive Podcast</i>, Dan Bruton &mdash; &ldquo;Rick Returns,&rdquo; on 15 years of PIE and Built Oregon","https://podcasts.apple.com/us/podcast/rick-returns-pie-built-oregon-co-founder-on-15-years/id1247188542?i=1000598535227"),
 ("2021","<i>PDX Executive Podcast</i>, Dan Bruton &mdash; building startup ecosystems and the evolution of tech community organizers","https://podcasts.apple.com/us/podcast/rick-turoczy-on-building-startup-ecosystems-and/id1247188542?i=1000532280101"),
 ("2017","<i>PR Talk</i>, Veracity Agency &mdash; &ldquo;Our Own Slice of PIE&rdquo;, on the PIE Cookbook and accelerating failure","https://www.veracityagency.com/podcast/rick-turoczy/"),
 ("2026","<i>My Open Source Experience</i> &mdash; the secrets to successful and sustainable events","https://www.youtube.com/watch?v=2h9yurfW0es"),
 ("2026","<i>Next Round VC</i> &mdash; the truth about startup accelerators","https://www.youtube.com/watch?v=IkeX3OZjfG4"),
 ("2025","Paden Squires &mdash; &ldquo;Grow Slow, Win Big: The Truth About the Compounding Effect&rdquo;","https://www.youtube.com/watch?v=sNQekLBGoZc"),
 ("2025","<i>FutureProof Business</i> &mdash; 30 years in startups: startup myths, VC truths, and building the Portland ecosystem","https://www.youtube.com/watch?v=WosfYTTAV8o"),
 ("2025","<i>The 5 Min Startup</i> &mdash; Episode 3, on why new businesses fail fast","https://www.youtube.com/watch?v=pbbAT6TcH-8"),
 ("2021","<i>The Communities Show</i>, Gamedev Camp &mdash; PIE, Built Oregon, TechfestNW, and the Portland startup community","https://www.youtube.com/watch?v=EIyNkXUrfY8"),
 ("2020","<i>Float Small Business</i> &mdash; Episode 6","https://www.youtube.com/watch?v=wKnK2BmHMwo"),
 ("2020","Millwork Commons &mdash; on the Portland startup community","https://www.youtube.com/watch?v=aVCeDXnT0nI"),
 ("2020","<i>Willamette Week</i> &mdash; Distant Voices, an early-pandemic conversation","https://www.youtube.com/watch?v=lG-ObTekUo0"),
 ("2017","The Tech Academy &mdash; Tech Talk","https://www.youtube.com/watch?v=0jsOaMwchew"),
 ("2015","<i>Launch Yourself</i>, Melissa Anzman &mdash; Session 28, on interacting more creatively","https://launchyourself.co/session28/"),
 ("2011","<i>GeekWire Radio</i>, John Cook &amp; Todd Bishop &mdash; sizing up the Seattle and Portland tech scenes","https://www.geekwire.com/2011/rewind-comparing-portland-seattle-tech-startup-scenes/"),
 ("2012","<i>GeekWire</i> &mdash; &ldquo;Four minutes on the train with&hellip; Portland startup guru Rick Turoczy of PIE&rdquo;","https://www.geekwire.com/2012/minutes-train-rick-turoczy/"),
 ("2020","<i>The Digital Native</i> &mdash; Episode 11, on PIE and structural incubator design","https://www.youtube.com/watch?v=bw2XY1gr3uM"),
 ("2025","<i>Startup Success</i>, Burkland &mdash; strategies for startups outside Silicon Valley","https://burklandassociates.com/podcasts/strategies-for-startups-outside-silicon-valley/"),
 ("2026","<i>The Intersection</i>, Intersectional Group &mdash; on founders socializing their concepts, blogging, curiosity, and abundance","https://www.iheart.com/podcast/269-the-intersection-presented-102288352/episode/its-really-important-for-founders-to-socialize-those-business-concepts-with-rick-turoczy-on-portlands-startup-community-blogging-long-live-silicon-florist-curiosity-and-abundance-318624657"),
 ("2018","<i>And Uhhh</i> &mdash; Episode 4","https://podcasts.apple.com/us/podcast/episode-4-rick-turoczy/id1347311606?i=1000412586971"),
 ("2025","<i>Overcommitted</i> &mdash; &ldquo;Navigating the Startup Landscape,&rdquo; on founder burnout and where startups actually fail","https://podcasts.apple.com/us/podcast/navigating-the-startup-landscape-with-rick-turoczy/id1804549260?i=1000735230674"),
 ("archival","<i>PushPull</i> &mdash; Episode 17, &ldquo;Startin&rsquo; Stuff&rdquo;","https://pushpull.me/episode/episode-17-startin-stuff"),
 ("2022","<i>Social Venturers</i> &mdash; S04E08, &ldquo;Succession Planning: Transferring Social Capital to the Next Generation&rdquo;","https://socialventurers.com/s04e08/"),
]),
("press", "Press and mentions", [
 ("2008","<i>The Oregonian</i> &mdash; Steve Woodward on Portland&rsquo;s early Twitter adoption","https://web.archive.org/web/20160315014332/http://www.oregonlive.com/special/index.ssf/2008/05/twitter_is_tweeter.html"),
 ("2009","PBS <i>The NewsHour with Jim Lehrer</i> &mdash; &ldquo;Tech Industry Faces Struggles Amid Economic Slump.&rdquo; Lee Hochberg reporting from Portland; I turn up on the chyron as a high-tech industry analyst, which was news to me.","https://web.archive.org/web/20090203074541/http://www.pbs.org:80/newshour/bb/business/jan-june09/techindustry_01-22.html"),
 ("2010","OregonLive / <i>The Oregonian</i> &mdash; &ldquo;30 Hour Day brings the telethon into the digital age&rdquo;","https://web.archive.org/web/20160310122439/http://www.oregonlive.com/entertainment/index.ssf/2010/06/30_hour_day_brings_the_teletho.html"),
 ("2011","<i>The Oregonian</i> &mdash; Mike Rogoway on the launch of PIE",""),
 ("2011","<i>GeekWire</i> &mdash; &ldquo;Google tosses support behind the Portland Incubator Experiment&rdquo;","https://www.geekwire.com/2011/google-tosses-support-portland-incubator-experiment/"),
 ("2011","<i>GeekWire</i> &mdash; &ldquo;Startup incubator reheats in Portland with help from Coke, Nike and Target&rdquo;","https://www.geekwire.com/2011/startup-tech-incubator-reheats-portland-ad-giant-wiedenkennedy/"),
 ("2011","<i>GeekWire</i> &mdash; &ldquo;Fast-growing startup BankSimple flees NYC for Portland: Here&rsquo;s why&rdquo;","https://www.geekwire.com/2011/fastgrowing-startup-banksimple-flees-nyc-portland/"),
 ("2011","<i>GeekWire</i> &mdash; &ldquo;Seattle and Portland should do more to become BFFs&rdquo; (guest column, mine)","https://www.geekwire.com/2011/seattle-portland-bffs/"),
 ("2011","<i>GeekWire</i> &mdash; Quotes of the Week, for publicly begging the internet to resurrect Kozmo","https://www.geekwire.com/2011/and-other-quotes-of-the-week/"),
 ("2012","<i>GeekWire</i> &mdash; &ldquo;Four minutes on the train with&hellip; Rick Turoczy of PIE&rdquo;","https://www.geekwire.com/2012/minutes-train-rick-turoczy/"),
 ("2012","<i>Willamette Week</i> &mdash; &ldquo;Exclusive: New PIE Class Announced&rdquo;","https://www.wweek.com/portland/blog-28909-exclusive-new-pie-class-announced.html"),
 ("2013","Business Wire &mdash; &ldquo;The Silicon Florist Shares Some Secrets of Growing Good Relationships with Bloggers&rdquo;","https://businesswired.wordpress.com/2013/01/24/the-silicon-florist-shares-some-secrets-of-growing-good-relationships-with-bloggers/"),
 ("2013","<i>Willamette Week</i> &mdash; &ldquo;TechfestNW 2013: Rick Turoczy&rdquo;","https://www.wweek.com/portland/article-21061-techfestnw-2013-rick-turoczy.html"),
 ("2014","<i>Portland Monthly</i> &mdash; &ldquo;Reasons to Love Portland: Rick Turoczy,&rdquo; Marty Patail, from the &ldquo;100 Reasons to Love Portland&rdquo; series","https://www.pdxmonthly.com/news-and-city-life/2014/06/rick-turoczy-june-2014"),
 ("2014","<i>Portland Business Journal</i> &mdash; &ldquo;Small Business Awards: Rick Turoczy gets startups off to great starts&rdquo;","https://www.bizjournals.com/portland/print-edition/2014/11/14/small-business-awards-rick-turoczy-gets-startups.html"),
 ("2014","<i>Willamette Week</i> &mdash; PIE Demo Day live stream and report",""),
 ("2015","<i>Portland Monthly</i> &mdash; &ldquo;Hot Tips from Portland&rsquo;s Financial Pros&rdquo;","https://www.pdxmonthly.com/news-and-city-life/2015/01/hot-tips-from-portlands-financial-pros-january-2015"),
 ("2015","<i>Oregon Business</i> &mdash; PIE plans to leave the Wieden+Kennedy building","https://oregonbusiness.com/12056-portland-incubator-experiment-plans-to-leave-wiedenkennedy-building/"),
 ("2015","<i>GeekWire</i> &mdash; PIE closes the accelerator, keeps helping startups","https://www.geekwire.com/2015/portland-incubator-experiment-closes-accelerator-but-still-focused-on-helping-startups/"),
 ("2016","Work With Flux &mdash; on the clearinghouse of 100+ Oregon companies hiring after the Intel layoffs","https://www.workwithflux.com/blog/2016/5/12/intel-layoffs-will-strain-oregon-hiring-capacity-but-help-emerges-for-job-seekers"),
 ("2016","TEDxPortland &mdash; Mara Zepeda and Samuel Hulick, &ldquo;Does technology make you feel more alive?&rdquo;. She calls me a fairy godfather of the Portland startup scene, from the stage, at 5:00.","https://www.youtube.com/watch?v=e4Iul863X-M&amp;t=300s"),
 ("2017","OPB <i>Think Out Loud</i> &mdash; &ldquo;Turkey Trouble | Lead Dust | Makers And Techs,&rdquo; with Marcelino Alvarez, on the split between Oregon&rsquo;s techs and its makers","https://www.opb.org/radio/programs/think-out-loud/article/turkey-lead-tech/"),
 ("2013","OPB <i>Think Out Loud</i> &mdash; &ldquo;Northwest Technology Update.&rdquo; The segment page is gone and nobody archived it.",""),
 ("2019","<i>Willamette Week</i> &mdash; &ldquo;Is Oregon Home to the Next Billion-Dollar Company?&rdquo;","https://www.wweek.com/news/2019/07/03/is-oregon-home-to-the-next-billion-dollar-company/"),
 ("2019","<i>Willamette Week</i> &mdash; &ldquo;Rick Turoczy Says the Myth of the Unflappable Entrepreneur Is All Bullshit&rdquo; (cover profile)","https://www.wweek.com/technology/2019/10/09/rick-turoczy-says-the-myth-of-the-unflappable-entrepreneur-is-all-bullshit/"),
 ("2020","Prosper Portland &mdash; Economic Recovery Task Force, listed across two work groups","https://prosperportland.us/wp-content/uploads/2020/05/Economic-Recovery-Task-Force-Meeting-2.pdf"),
 ("2021","<i>GeekWire</i> &mdash; mpathic and &ldquo;empathy-as-a-service&rdquo; at PIE Demo Day","https://www.geekwire.com/2021/startup-aims-improve-workplace-conversations-empathy-service-software/"),
 ("2021","<i>Willamette Week</i> &mdash; &ldquo;What If You Could Pour Your Own Shampoo From a Tap?&rdquo;","https://www.wweek.com/technology/2021/07/02/what-if-you-could-pump-your-own-shampoo/"),
 ("2008&ndash;09","<i>ReadWriteWeb</i> &mdash; bylined writer on the open web, APIs, and developer hubs outside California","http://web.archive.org/web/20120116011447/http://www.readwriteweb.com:80/archives/readwriteweb_expands_silicon_forest_empire.php"),
]),
("deck", "Writing", [
 ("2026","<i>It Takes a Valley</i>, Anika Horn &mdash; a practitioner&rsquo;s book about the people who build the ecosystems that make entrepreneurship possible. I turn up in it.","https://bookshop.org/p/books/it-takes-a-valley-how-to-build-thriving-entrepreneurial-ecosystems-that-transform-our-communities-anika-horn/24830809?aid=128693&amp;ean=9798995796312&amp;listref=startup-books"),
 ("2020","<i>The Startup Community Way</i>, Brad Feld and Ian Hathaway &mdash; on building complex, founder-led regional ecosystems. I turn up in this one too.","https://bookshop.org/p/books/the-startup-community-way-evolving-an-entrepreneurial-ecosystem-brad-feld/16653612?aid=128693&amp;ean=9781119613602&amp;listref=startup-books"),
 ("2017","<i>Portland Makers: How to Build a Creative Community</i> &mdash; ポートランド・メイカーズ. Mitsuya Mazaki interviewed me in 2016; my words came out in Japanese, and later Korean.","https://book.gakugei-pub.co.jp/gakugei-book/9784761526429/"),
 ("2016&ndash;17","<i>The PIE Cookbook</i> &mdash; everything we learned running PIE, written down and given away open source so any community could run its own accelerator. Kickstarted in 2016; the 0.9 beta landed in 2017.","https://siliconflorist.com/2017/04/04/an-initial-taste-of-the-pie-cookbook/"),
 ("","<i>Brand Signals</i> &mdash; 150 slides on positioning and the things a brand says without saying them","https://www.slideshare.net/slideshow/brand-signals/21148"),
 ("","<i>Inspiring Illogical Decisions</i> &mdash; 50 slides on conviction over incrementalism","https://www.slideshare.net/slideshow/inspiring-illogical-decisions/7124543"),
 ("","<i>A Series of Happy Accidents</i> &mdash; 48 slides on how Portland&rsquo;s scene actually happened","https://www.slideshare.net/slideshow/a-series-of-happy-accidents/55054257"),
 ("","<i>Ideas About Ideas</i> &mdash; 30 slides training executives to mentor founders","https://speakerdeck.com/turoczy/ideas-about-ideas"),
 ("","<i>How to Bake PIE</i> &mdash; 37 slides on accelerator mechanics and cohort design","https://www.slideshare.net/slideshow/how-to-bake-pie-10474833/10474833"),
 ("","<i>PIE: How to Meet</i> &mdash; 18 slides on how a founder meeting should actually go","https://www.slideshare.net/slideshow/pie-how-to-meet/16007393"),
 ("","<i>OEN Social Media 101</i> &mdash; 83 slides of workshop for the Oregon Entrepreneurs Network","https://www.slideshare.net/slideshow/oen-social-media-101-presentation/725914"),
 ("","<i>Tiny Startup Camp: Social Media</i> &mdash; 21 slides, the short version","https://www.slideshare.net/slideshow/tiny-startup-camp-social-media/15146387"),
 ("","<i>2008 Portland Tech Recap</i> &mdash; 64 slides, for PDX Web Innovators","https://www.slideshare.net/slideshow/2008-portland-tech-recap-presentation/816775"),
 ("2025","<i>AI Is Revolutionizing Startup Growth Opportunities Now</i>","https://www.youtube.com/watch?v=dhiYkJBzA5M"),
 ("2025","<i>Securing Funding for Startups Beyond Silicon Valley</i>","https://www.youtube.com/watch?v=QgQlhhBr1eo"),
 ("2022","Founder University &mdash; <i>How to Write Investor Updates</i>, plus the metrics that matter (CAC, LTV, churn)","https://www.youtube.com/watch?v=dgz-Ud4fq6w"),
 ("2020","PIE AMA &mdash; <i>How to find investors in the Portland startup community</i>","https://www.youtube.com/watch?v=tuB_Sc09dmw"),
 ("2020","PIE AMA &mdash; <i>How to join the Portland startup community</i>","https://www.youtube.com/watch?v=x3VeNA8oD60"),
 ("","Masterclasses on YouTube &mdash; starting a startup before building or funding, what founders are actually like, how to mentor, how to Portland startup community",YT),
]),
("kick", "Kickstarter campaigns", [
 ("2016","<i>PIE Cookbook: An Open Source Guide for Startup Accelerators</i> &mdash; crowdfunding the work of writing down everything we learned running PIE, and giving it away","https://www.kickstarter.com/projects/turoczy/pie-cookbook-an-open-source-guide-for-startup-acce"),
 ("2014","<i>Built Oregon</i> &mdash; funding a statewide storytelling project for Oregon&rsquo;s consumer product founders, because nobody was telling those stories either","https://www.kickstarter.com/projects/130336980/built-oregon/"),
]),
("ksback", "Kickstarter investments", [
 ("","<i>Hasaan Hates Portland</i>","https://www.kickstarter.com/projects/mischawebley/hasaan-hates-portland"),
 ("","<i>It Takes a Valley</i>","https://www.kickstarter.com/projects/ittakesavalley/it-takes-a-valley"),
 ("","<i>Adventure Hoodie</i>","https://www.kickstarter.com/projects/lamprey/adventurehoodie"),
 ("","<i>Plant Simple - Classic sauces, made plant-based.</i>","https://www.kickstarter.com/projects/1422945683/plant-simple-classic-sauces-made-plant-based"),
 ("","<i>Cütie Catcherz: One Shot</i>","https://www.kickstarter.com/projects/eyelndfeevrar/cutie-catcherz-one-shot"),
 ("","<i>Refactoring English</i>","https://www.kickstarter.com/projects/mtlynch/refactoring-english"),
 ("","<i>The Book of Shame: An Extra Fabulous Experience</i>","https://www.kickstarter.com/projects/extrafabulous/the-book-of-shame-an-extra-fabulous-experience"),
 ("","<i>Twisted Cryptids</i>","https://www.kickstarter.com/projects/ramybadie/twisted-cryptids"),
 ("","<i>BACKFENCE Storytelling - True Stories for Everyone!</i>","https://www.kickstarter.com/projects/289221627/backfence-storytelling-true-stories-for-everyone"),
 ("","<i>the NEW adventure hoodie with 23+ features and innovations</i>","https://www.kickstarter.com/projects/pleep/yay"),
 ("","<i>Mr. Lovenstein Presents: FEELINGS</i>","https://www.kickstarter.com/projects/mrlovenstein/presents-feelings"),
 ("","<i>Command of Nature</i>","https://www.kickstarter.com/projects/ramybadie/command-of-nature"),
 ("","<i>CardCraft - We believe in the Power of Connection</i>","https://www.kickstarter.com/projects/cardcraft/cardcraft-we-believe-in-the-power-of-connection"),
 ("","<i>Draplin Design Company Brand Tumbling Dice - Limited Edition</i>","https://www.kickstarter.com/projects/justinsirois/draplin-design-company-cee-lo-dice-limited-edition"),
 ("","<i>BLADE RUNNER – The Roleplaying Game</i>","https://www.kickstarter.com/projects/1192053011/blade-runner-the-roleplaying-game"),
 ("","<i>Mastering the Game of Allyship</i>","https://www.kickstarter.com/projects/wendell-britt/mastering-the-game-of-allyship"),
 ("","<i>Lost for Words</i>","https://www.kickstarter.com/projects/amibaio/lost-for-words"),
 ("","<i>Momentum Planner</i>","https://www.kickstarter.com/projects/teampf/momentum-planner"),
 ("","<i>Rabbit Rabbit: A Game of Superstitions</i>","https://www.kickstarter.com/projects/amibaio/rabbit-rabbit-a-game-of-superstitions"),
 ("","<i>A Kids Book About COVID-19: Print Edition &amp; Translations</i>","https://www.kickstarter.com/projects/akidsbookabout/a-kids-book-about-covid-19-print-edition-and-translations"),
 ("","<i>Flatter Me: A Compliment Battle Card Game</i>","https://www.kickstarter.com/projects/amibaio/flatter-me-a-compliment-battle-card-game"),
 ("","<i>DORSUM EXOSPINE</i>","https://www.kickstarter.com/projects/dorsum-superbrace/dorsum-exospine-dorsumtechcom"),
 ("","<i>Save Cameron&rsquo;s Books, EST. 1938</i>","https://www.kickstarter.com/projects/cameronsbooks1938/save-camerons-books-est-1938"),
 ("","<i>Throw Throw Burrito</i>","https://www.kickstarter.com/projects/elanlee/throw-throw-burrito"),
 ("","<i>Performance Sunglasses Built to Last and Backed for Life</i>","https://www.kickstarter.com/projects/revantoptics/performance-sunglasses-built-to-last-and-backed-fo"),
 ("","<i>AllGo - An Accessibility App for Plus-Size People</i>","https://www.kickstarter.com/projects/canweallgo/allgo-an-accessibility-app-for-plus-size-people"),
 ("","<i>WE ARE CHANGE AGENTS.</i>","https://www.kickstarter.com/projects/707440663/we-are-change-agents"),
 ("","<i>Get Your Money Together: your purr-fect finance workbook</i>","https://www.kickstarter.com/projects/anomalily/get-your-money-together-your-purr-fect-finance-wor"),
 ("","<i>Brain Fuel - a unique brainstorming tool</i>","https://www.kickstarter.com/projects/frisovisser/brain-fuel-a-unique-brainstorming-tool"),
 ("","<i>Unstable Unicorns</i>","https://www.kickstarter.com/projects/ramybadie/unstable-unicorns"),
 ("","<i>Publicly Traded, Privately Held</i>","https://www.kickstarter.com/projects/kmikeym/publicly-traded-privately-held"),
 ("","<i>CANVAS: A Revolutionary New Beverage Made from &rsquo;Saved Grain&rsquo;</i>","https://www.kickstarter.com/projects/savethebarley/canvas-a-new-type-of-beverage-made-from-saved-grai"),
 ("","<i>Make it Green</i>","https://www.kickstarter.com/projects/zoeg/make-it-green"),
 ("","<i>Pitch Deck</i>","https://www.kickstarter.com/projects/fred/pitch-deck"),
 ("","<i>100 Postcards from Amsterdam</i>","https://www.kickstarter.com/projects/boaz/100-postcards-from-amsterdam"),
 ("","<i>Indie Microblogging: owning your short-form writing</i>","https://www.kickstarter.com/projects/manton/indie-microblogging-owning-your-short-form-writing"),
 ("","<i>Bears vs Babies - A Card Game</i>","https://www.kickstarter.com/projects/elanlee/bears-vs-babies-a-card-game"),
 ("","<i>Cereal - 250 Daily Treats For The Every Day Entrepreneur</i>","https://www.kickstarter.com/projects/yis/cereal-250-daily-treats-for-the-every-day-entrepre"),
 ("","<i>The Startup Mixtape</i>","https://www.kickstarter.com/projects/elliottadams/the-startup-mixtape"),
 ("","<i>The Responsible Communication Style Guide</i>","https://www.kickstarter.com/projects/961164339/the-responsible-communication-style-guide"),
 ("","<i>&ldquo;This is Fine&rdquo; Plush Dog.</i>","https://www.kickstarter.com/projects/kcgreen/this-is-fine-plush-dog"),
 ("","<i>A New Home: The IPRC Relocation Project</i>","https://www.kickstarter.com/projects/1078496550/a-new-home-the-iprc-relocation-project"),
 ("","<i>Chuck Palahniuk&rsquo;s Lullaby</i>","https://www.kickstarter.com/projects/footsteps/chuck-palahniuks-lullaby"),
 ("","<i>Audibility Customs: Custom-Fit Headphones</i>","https://www.kickstarter.com/projects/audibility/audibility-customs-custom-fit-headphones"),
 ("","<i>Brixo - Building Blocks Meet Electricity and IoT</i>","https://www.kickstarter.com/projects/1068475467/brixo-building-blocks-meet-electricity-and-iot"),
 ("","<i>Pistol Lake: Ultra-functional activewear for minimalists</i>","https://www.kickstarter.com/projects/wsul/pistol-lake-ultra-functional-activewear-for-minima"),
 ("","<i>Love Wins- A Powerful Book of LGBTQ Love Stories</i>","https://www.kickstarter.com/projects/giagoodrichpdx/love-wins-a-powerful-book-of-lgbtq-love-stories"),
 ("","<i>Retrofit Comics 2016: 12 New Graphic Novels &amp; Comics</i>","https://www.kickstarter.com/projects/retrofitcomics/retrofit-comics-2016-6-new-graphic-novels-and-comi"),
 ("","<i>CreativeMornings: support the volunteers who make it happen!</i>","https://www.kickstarter.com/projects/swissmiss/creativemornings-support-the-volunteers-who-make-i"),
 ("","<i>&ldquo;Oi&rdquo; - The bike bell that doesn&rsquo;t look like a bike bell</i>","https://www.kickstarter.com/projects/knog/oi-the-bike-bell-that-doesnt-look-like-a-bike-bell"),
 ("","<i>Snow Monkey Subzero Superfood: Ice Cream For Breakfast?</i>","https://www.kickstarter.com/projects/snowmonkey/subzero-superfood-ice-cream-for-breakfast"),
 ("","<i>Walking with Ramona: Exploring Beverly Cleary&rsquo;s Portland</i>","https://www.kickstarter.com/projects/microcosmpublishing/walking-with-ramona-exploring-beverly-clearys-port"),
 ("","<i>Joking Hazard</i>","https://www.kickstarter.com/projects/cyanideandhappiness/joking-hazard"),
 ("","<i>OSSIC X: The first 3D audio headphones calibrated to you</i>","https://www.kickstarter.com/projects/248983394/ossic-x-the-first-3d-audio-headphones-calibrated-t"),
 ("","<i>MOGICS Power Donut &amp; Bagel - Share the Power, Save the Space</i>","https://www.kickstarter.com/projects/mogics/mogics-power-donut-and-bagel-share-the-power-save"),
 ("","<i>Prepd Pack - The Lunchbox Reimagined</i>","https://www.kickstarter.com/projects/prepd/prepd-pack"),
 ("","<i>Python Jumpstart by Building 10 Apps [video course]</i>","https://www.kickstarter.com/projects/mikeckennedy/python-jumpstart-by-building-10-apps-video-course"),
 ("","<i>The Suck Less Job Search</i>","https://www.kickstarter.com/projects/603136401/the-suck-less-job-search"),
 ("","<i>Columbia Gorge Getaways: The 1st Comprehensive Gorge Guide</i>","https://www.kickstarter.com/projects/1310192708/columbia-gorge-getaways-the-1st-comprehensive-gorg"),
 ("","<i>Bring &ldquo;Thank You For Playing&rdquo; To Theaters/Screens Worldwide!</i>","https://www.kickstarter.com/projects/1372561818/bring-thank-you-for-playing-to-theaters-screens-wo"),
 ("","<i>The Offworld Collection</i>","https://www.kickstarter.com/projects/1315256652/the-offworld-collection"),
 ("","<i>PEN America presents Passages</i>","https://www.kickstarter.com/projects/penamerican/pen-america-presents-passages"),
 ("","<i>THE DISSIDENT</i>","https://www.kickstarter.com/projects/panderbrothers/the-dissident-full-color-interactive-digital-comic"),
 ("","<i>The Ultimate Stylish and Fully Functional Commuting Jackets</i>","https://www.kickstarter.com/projects/k-9/the-ultimate-stylish-and-fully-functional-commutin"),
 ("","<i>Olympia Oyster Bar, Oysters for Everyone!</i>","https://www.kickstarter.com/projects/1009938995/olympia-oyster-bar-oysters-for-everyone"),
 ("","<i>The Super Fleece by Rumpl: The Perfect Blanket for Your Bed</i>","https://www.kickstarter.com/projects/rumpl/the-super-fleece-by-rumpl-the-perfect-blanket-for"),
 ("","<i>Where the Heck is Matt?</i>","https://www.kickstarter.com/projects/wheretheheckismatt/where-the-heck-is-matt"),
 ("","<i>WooBots - Transformable Wooden Robot</i>","https://www.kickstarter.com/projects/1952108245/woobots"),
 ("","<i>ZILLA and ZOE: The Movie</i>","https://www.kickstarter.com/projects/630743900/zilla-and-zoe-the-movie"),
 ("","<i>The Wonderful World of Creatures &amp; Code</i>","https://www.kickstarter.com/projects/1164329758/the-wonderful-world-of-creatures-and-code"),
 ("","<i>XO: a retro sci-fi strategy game for PC/Mac/Linux</i>","https://www.kickstarter.com/projects/jumpdrive/xo-a-retro-sci-fi-strategy-game-for-pc-mac-linux"),
 ("","<i>Flying Fish Food Revolution</i>","https://www.kickstarter.com/projects/ffpdx2026/flying-fish-food-revolution"),
 ("","<i>Priced Out: Gentrification beyond black and white</i>","https://www.kickstarter.com/projects/562086297/priced-out-15-years-of-gentrification-in-portland"),
 ("","<i>Know Your City: Sustain our new projects into 2016!</i>","https://www.kickstarter.com/projects/1607251927/know-your-city-sustain-our-new-projects-into-2016"),
 ("","<i>Neocities 3.0: An interactive HTML/CSS course for everyone</i>","https://www.kickstarter.com/projects/1262953102/neocities-30-an-interactive-html-css-course-for-ev"),
 ("","<i>Help Us To #RewriteTheCode: The #ProjectDiane Documentary</i>","https://www.kickstarter.com/projects/digitalundivided/help-us-to-rewritethecode-the-projectdiane-documen"),
 ("","<i>THE JENNINGS HOTEL – The Hotel That Kickstarter Built</i>","https://www.kickstarter.com/projects/thejenningshotel/the-jennings-hotel-the-hotel-that-kickstarter-buil"),
 ("","<i>Adaptive Saber Parts - Make your dream lightsaber a reality.</i>","https://www.kickstarter.com/projects/1621134222/adaptive-saber-parts-make-your-dream-lightsaber-a"),
 ("","<i>The Product Hunt Effect</i>","https://www.kickstarter.com/projects/1845561887/the-product-hunt-effect"),
 ("","<i>CHIP - The World&rsquo;s First Nine Dollar Computer</i>","https://www.kickstarter.com/projects/1598272670/chip-the-worlds-first-9-computer"),
 ("","<i>Aletruism Brewing: Have a pint, change the world.</i>","https://www.kickstarter.com/projects/2070530201/aletruism-brewing-have-a-pint-change-the-world"),
 ("","<i>Only on Kickstarter: THE LEADER&rsquo;S GUIDE by ERIC RIES</i>","https://www.kickstarter.com/projects/881308232/only-on-kickstarter-the-leaders-guide-by-eric-ries"),
 ("","<i>Women In Tech: The Book!</i>","https://www.kickstarter.com/projects/tarahwheelervanvlack/women-in-tech-the-book"),
 ("","<i>Society Nine - The brand for badass women.</i>","https://www.kickstarter.com/projects/societynine/society-nine-the-brand-for-badass-women"),
 ("","<i>TLC is BACK to make our FINAL ALBUM with YOU!</i>","https://www.kickstarter.com/projects/1507621537/tlc-is-back-to-make-our-final-album-with-you"),
 ("","<i>Exploding Kittens</i>","https://www.kickstarter.com/projects/elanlee/exploding-kittens"),
 ("","<i>Yellow Scope: A Different Kind of Science Kit for Girls</i>","https://www.kickstarter.com/projects/yellow-scope-science/yellow-scope-a-different-kind-of-science-kit-for-g"),
 ("","<i>Betabook: The Portable Whiteboard for the Digital Age</i>","https://www.kickstarter.com/projects/betabook/betabook-the-portable-whiteboard-for-the-digital-a"),
 ("","<i>The uKeg Pressurized Growler for Fresh Beer</i>","https://www.kickstarter.com/projects/growlerwerks/the-ukegtm-pressurized-growler-for-fresh-beer"),
 ("","<i>Women&rsquo;s Jeans in 400 Sizes : Made-to-Order by Qcut</i>","https://www.kickstarter.com/projects/crystalbeasley/womens-jeans-in-400-sizes-made-to-order-by-qcut"),
 ("","<i>Built Oregon</i>","https://www.kickstarter.com/projects/130336980/built-oregon"),
 ("","<i>Whiskey Elements: Customize your Whiskey in 24 hours</i>","https://www.kickstarter.com/projects/263766519/whiskey-elements-customize-your-whiskey-in-24-hour"),
 ("","<i>The Manual, Everywhere</i>","https://www.kickstarter.com/projects/goodonpaper/the-manual-everywhere"),
 ("","<i>Exhibition Kickstarter</i>","https://www.kickstarter.com/projects/ksouth/exhibition-kickstarter"),
 ("","<i>GripSnap: the magnetic holder for smartphones and GoPros</i>","https://www.kickstarter.com/projects/143547447/gripsnap-the-coolest-multi-use-monopod-with-a-magn"),
 ("","<i>COOLEST COOLER: 21st Century Cooler that&rsquo;s Actually Cooler</i>","https://www.kickstarter.com/projects/ryangrepper/coolest-cooler-21st-century-cooler-thats-actually"),
 ("","<i>Tickle: Learn to Code to make iPhone+iPad Apps and Games</i>","https://www.kickstarter.com/projects/705926089/tickle-learn-to-code-using-scratch-to-make-iphone"),
 ("","<i>New Album</i>","https://www.kickstarter.com/projects/fallingup/new-album-1"),
 ("","<i>The Return of Upcoming.org</i>","https://www.kickstarter.com/projects/waxpancake/the-return-of-upcomingorg"),
 ("","<i>Pijin: Flock, talk &amp; unlock the sensory puzzles of speech</i>","https://www.kickstarter.com/projects/travisfeldman/pijin-the-spelling-game-of-the-spoken-word"),
 ("","<i>The Great Discontent Magazine, Issue 1</i>","https://www.kickstarter.com/projects/essmaker/the-great-discontent-magazine-issue-1"),
 ("","<i>Everydisk – Easily access all your computers, from anywhere.</i>","https://www.kickstarter.com/projects/avatron/everydisk-easily-access-all-your-computers-from-an"),
 ("","<i>Periscope Studio: Maiden Voyage</i>","https://www.kickstarter.com/projects/periscopestudio/periscope-studio-maiden-voyage"),
 ("","<i>KeyBit - MagSafe Adapter Key Ring</i>","https://www.kickstarter.com/projects/jbobrow/keybit-magsafe-adapter-key-ring"),
 ("","<i>Hunter Thompson: The Cozumel Diary</i>","https://www.kickstarter.com/projects/1934661728/hunter-thompson-the-cozumel-diary"),
 ("","<i>ME, FAKEGRIMLOCK: THE BOOK OF AWESOME</i>","https://www.kickstarter.com/projects/531215105/me-fakegrimlock-the-book-of-awesome"),
 ("","<i>GUSTIN: Redefining premium menswear, starting with denim.</i>","https://www.kickstarter.com/projects/weargustin/gustin-redefining-premium-menswear-starting-with-d"),
 ("","<i>Star Wars and Mustaches T-Shirt &amp; Blockprints</i>","https://www.kickstarter.com/projects/793732707/star-wars-and-mustaches-tee"),
 ("","<i>THE ONE MOTORCYCLE SHOW BOOKS V1 &amp; V2</i>","https://www.kickstarter.com/projects/1315921470/the-one-motorcycle-show-books-v1-and-v2"),
 ("","<i>Monsters Ate My Birthday Cake</i>","https://www.kickstarter.com/projects/sleepninja/monsters-ate-my-birthday-cake"),
 ("","<i>FlatLight</i>","https://www.kickstarter.com/projects/488871743/flatlight"),
 ("","<i>AirTracks: Inflatable All-Terrain Camera Slider</i>","https://www.kickstarter.com/projects/baker/airtracks-inflatable-all-terrain-camera-slider"),
 ("","<i>Hop in the Saddle</i>","https://www.kickstarter.com/projects/1548588607/hop-in-the-saddle"),
 ("","<i>Molecule Synth:An Electronic Musical Instrument for Everyone</i>","https://www.kickstarter.com/projects/travisfeldman/molecule-synth"),
 ("","<i>The Humble Velocipede</i>","https://www.kickstarter.com/projects/thehumblevelocipede/the-humble-velocipede"),
 ("","<i>The Portland Sessions</i>","https://www.kickstarter.com/projects/theportlandsessions/the-portland-sessions"),
 ("","<i>Stealing Time Magazine, vol I, iss 1: Genesis</i>","https://www.kickstarter.com/projects/sarahgilbert/stealing-time-magazine-vol-i-iss-1-genesis"),
 ("","<i>Know Your City: Portland&rsquo;s Social History App 2.0!</i>","https://www.kickstarter.com/projects/dillpickleclub/know-your-city-portlands-social-history-app-20"),
 ("","<i>Twig: the amazing ultra-portable cable for your iPhone</i>","https://www.kickstarter.com/projects/utensile/twig-the-amazing-ultra-portable-cable-for-your-iph"),
 ("","<i>Darth Across America</i>","https://www.kickstarter.com/projects/julieschu/darth-across-america"),
 ("","<i>Trygger Camera Case: iPhone 4/4S Polarizing Filter Case</i>","https://www.kickstarter.com/projects/trygger/trygger-camera-case-iphone-4-4s-polarizing-filter"),
 ("","<i>XOXO Festival</i>","https://www.kickstarter.com/projects/waxpancake/xoxo-festival"),
 ("","<i>Pebble: E-Paper Watch for iPhone and Android</i>","https://www.kickstarter.com/projects/getpebble/pebble-e-paper-watch-for-iphone-and-android"),
 ("","<i>Light Table</i>","https://www.kickstarter.com/projects/ibdknox/light-table"),
 ("","<i>Cultured Caveman: Portland&rsquo;s first 100% paleo food cart</i>","https://www.kickstarter.com/projects/culturedcaveman/cultured-caveman-portlands-first-100-paleo-food-ca"),
 ("","<i>This Book Is About Travel (A Manual For Modern Movement)</i>","https://www.kickstarter.com/projects/andrewhyde/this-book-is-about-travel"),
 ("","<i>The HuMn Wallet - the best minimal RFID blocking wallet</i>","https://www.kickstarter.com/projects/1127228691/the-humn-wallet-the-best-minimal-rfid-blocking-wal"),
 ("","<i>CASH Music Platform</i>","https://www.kickstarter.com/projects/cashmusic/cash-music-platform"),
 ("","<i>ZOOKA™ - Wireless Speaker for your iPad, iPhone &amp; iPod</i>","https://www.kickstarter.com/projects/traito/zooka-bluetooth-speaker-for-your-ipad"),
 ("","<i>Elevation Dock: The Best Dock For iPhone</i>","https://www.kickstarter.com/projects/hop/elevation-dock-the-best-dock-for-iphone"),
 ("","<i>TOAST: Functional bling for your iPhone!</i>","https://www.kickstarter.com/projects/2101651398/toast-functional-bling-for-your-iphone"),
 ("","<i>Computing: a Documentary of the Human Experience</i>","https://www.kickstarter.com/projects/1747241049/computing-a-documentary-of-the-human-experience"),
 ("","<i>The Uprise Books Project</i>","https://www.kickstarter.com/projects/uprisebooksproject/the-uprise-books-project-fighting-poverty-with-ban"),
 ("","<i>Preview “Design for Hackers” by backing the book tour</i>","https://www.kickstarter.com/projects/kadavy/preview-design-for-hackers-by-backing-the-book-tou"),
 ("","<i>ISS-Notify</i>","https://www.kickstarter.com/projects/natronics/iss-notify"),
 ("","<i>A New Season of Destination DIY</i>","https://www.kickstarter.com/projects/destinationdiy/a-new-season-of-destination-diy"),
 ("","<i>RDTN.org: Radiation Detection Hardware Network in Japan</i>","https://www.kickstarter.com/projects/1038658656/rdtnorg-radiation-detection-hardware-network-in-ja"),
]),
("invest", "Things I&rsquo;ve invested in", [
 ("","<i>Airship</i> (neé Urban Airship) &mdash; Portland mobile engagement platform that grew out of the PIE coworking space and went on to raise more than $100M","https://www.airship.com/"),
 ("","<i>Backstage Capital</i> &mdash; Arlan Hamilton&rsquo;s fund backing founders who are underrepresented, underestimated, and usually overlooked","https://backstagecapital.com/"),
 ("","<i>Bison Venture Partners</i> &mdash; Garry Johnson III&rsquo;s outfit working to get investment dollars to Black founders, and lately to get founders AI infrastructure they actually own","https://wefunder.com/bisonvp"),
 ("","<i>Calm Company Fund</i> &mdash; Tyler Tringas&rsquo;s fund for profitable, sustainable software companies that never wanted to be unicorns. I scouted for them, too","https://wefunder.com/calmfund"),
 ("","<i>Customer.io</i> &mdash; Portland customer messaging platform, and a charter member of the quiet generation of Portland startups that just execute","https://customer.io/"),
 ("","<i>Freeland Spirits</i> &mdash; Jill Kuehler&rsquo;s women-owned Portland distillery, where the grain is grown on Cory Carman&rsquo;s Oregon ranch and everything else starts from scratch","https://freelandspirits.com/"),
 ("","<i>Graze</i> &mdash; feed-building on Bluesky&rsquo;s open social protocol, so the algorithm is yours instead of somebody else&rsquo;s","https://www.graze.social/"),
 ("","<i>Riff</i> &mdash; Bend cold brew coffee, since reinvented as an energy drink. My position is marked failed, which is how a fair number of these go","https://letsriff.com/"),
 ("","<i>The Sports Bra</i> &mdash; Jenny Nguyen&rsquo;s bar that only shows women&rsquo;s sports, which turned out to be a very good idea","https://thesportsbraofficial.com/"),
 ("","<i>Tender Loving Empire</i> &mdash; Portland record label and craft shops, proving you can build a company out of making things by hand","https://tenderlovingempire.com/"),
]),
("org", "Organizing", [
 ("2011&ndash;21","<i>TechfestNW</i> &mdash; cofounder and programming curator, with <i>Willamette Week</i>. Multi-track stages, international speakers. <i>Fortune</i> called it &ldquo;the next SXSW,&rdquo; which was generous.","https://web.archive.org/web/20250926091357/https://www.techfestnw.com/"),
 ("2009&ndash;10","<i>30 Hour Day</i> &mdash; a 30-hour livestreamed telethon run out of PIE for Oregon Food Bank, Free Geek, and Toys for Tots. 77,000 viewers, nearly $10,000 raised, and we did it twice.","https://siliconflorist.com/2014/12/19/years-portlands-startup-scene-approaching-long-incredibly-rewarding-day/"),
 ("2015&ndash;","<i>Portland Startups Slack</i> &mdash; started it to find out whether a chat room could recreate the early Twitter magic of the Portland startup scene. It could. More than 8,000 profiles now, most of them cheerfully dormant.","https://join.slack.com/t/pdxstartups/shared_invite/zt-3hlwhx3n8-wivK0d2Kwj7sHCI_qSwgew"),
 ("2014&ndash;","<i>Portland Startups Switchboard</i> &mdash; launched with PIE alum Switchboard, so folks could Ask for what they need and Offer what they have. Nearly 2,000 people in the first year, and it&rsquo;s still going.","https://pdxstartups.switchboardhq.com/"),
 ("multiple","<i>PIE Demo Days</i> &mdash; the day each cohort graduates into the ecosystem. Bittersweet every time.","https://www.piepdx.com/"),
 ("2008&ndash;09","<i>Open Source Bridge</i> &mdash; marketing lead for the first one, after OSCON left town","https://web.archive.org/web/20090305100212/http://opensourcebridge.org/"),
 ("2023&ndash;","<i>Pitch Black</i> &mdash; production crew. Stephen Green&rsquo;s pitch competition for Black founders, and the best pitch event in Portland. Every dollar goes to the founders as non-dilutive grants.","https://www.pitchblack.org/"),
 ("2019","<i>Startup Champions Network Spring Summit</i> &mdash; lead organizer and local host, with PIE. Ecosystem builders from around the country spent 2.5 days in Portland, March 19&ndash;21, with panels at the Wacom Experience Center, a public reception at Tilt on East Burnside, and site visits across the city.","https://siliconflorist.com/2019/11/14/revisiting-the-startup-champions-network-portland-visit/"),
 ("2014&ndash;20","<i>Portland Startup Week</i> &mdash; started it and ran the programming, then handed it off in 2020. It outlasted me by six years and survived a pandemic before being retired in 2026 in favor of a statewide Oregon Startup Week.","https://siliconflorist.com/2014/10/14/portland-startup-week-design-week-portland-startup-awesomeness/"),
 ("2016","<i>Intel Outside</i> &mdash; lead organizer. A free community job fair at the Falcon Building for the ~800 Portlanders laid off by Intel, built from a blog post to nearly 200 supporting companies in four weeks, with no budget.","https://siliconflorist.com/2016/05/24/escalated-quickly-join-free-portland-community-job-fair-june-1-falcon-building/"),
 ("2013","<i>Hack @ Hayward</i> &mdash; Eugene, with Intel, Oregon Film, and TrackTown USA. Two days at Hayward Field imagining the fan experience ahead of the World Junior Championships.",""),
 ("2012","<i>Portland Narrative Hack</i> &mdash; a day with Intel, Wieden+Kennedy, and Oregon Film, hacking the future of interactive storytelling. Sixteen people, no rules. It became Oregon Story Board.","https://vimeo.com/44539955"),
 ("2017&ndash;","<i>Built Festival</i> &mdash; Built Oregon&rsquo;s annual gathering of the state&rsquo;s consumer product founders, makers, and retailers. Started as Built Up Festival in 2017; 700 people across 17 events that first week.","https://www.builtoregon.com/"),
]),
]

def end_year(t):
    t = t.replace('&ndash;','-').strip()
    if not re.search(r'\d', t): return -1
    m = re.match(r'^(\d{4})\s*-\s*(\d{4})$', t)
    if m: return int(m.group(2))
    m = re.match(r'^(\d{4})\s*-\s*(\d{2})$', t)
    if m: return int(m.group(1)[:2]+m.group(2))
    if re.match(r'^\d{4}\s*-\s*$', t): return 9999
    ys = [int(x) for x in re.findall(r'\d{4}', t)]
    return max(ys) if ys else -1

def start_year(t):
    ys = [int(x) for x in re.findall(r'\d{4}', t.replace('&ndash;','-'))]
    return min(ys) if ys else -1

total = sum(len(g[2]) for g in GROUPS)

L = ['  <section class="section" id="index">',
     '    <div class="section-grid">',
     '      <div class="section-head"><h2>Index</h2></div>',
     '      <div class="section-body">',
     '        <p class="lede">Everything I can find a record of &mdash; %d entries and counting. Some of it I remember fondly. Some of it I remember differently than the people who were there.</p>' % total,
     '',
     '        <div class="filters" role="group" aria-label="Filter the index">',
     '          <button type="button" class="chip" data-filter="all" aria-pressed="true">Everything</button>']
for key, lab in [("talk","Talks"),("show pod","Shows"),("press","Press"),("deck","Writing"),("kick ksback","Kickstarters"),("invest","Investments"),("org","Organizing")]:
    L.append('          <button type="button" class="chip" data-filter="%s" aria-pressed="false">%s</button>' % (key, lab))
L.append('        </div>')

for key, title, rows in GROUPS:
    ordered = sorted(enumerate(rows), key=lambda t: (-end_year(t[1][0]), -start_year(t[1][0]), t[0]))
    L.append('')
    L.append('        <section class="ix-group" data-group="%s">' % key)
    L.append('          <h3 class="ix-title">%s</h3>' % title)
    L.append('          <ul class="ix">')
    for _, (yr, what, url) in ordered:
        # the entry text IS the link
        body = '<a class="ix-entry" href="%s">%s</a>' % (url, what) if url else what
        L.append('            <li><span class="ix-yr">%s</span><span class="ix-what">%s</span></li>' % (yr or '&nbsp;', body))
    L.append('          </ul>')
    L.append('        </section>')

L += ['',
      '        <p class="ix-note">Missing something? I probably forgot it. <a href="mailto:rick@piepdx.com?subject=You%20forgot%20one">Tell me</a> and I&rsquo;ll add it.</p>',
      '      </div>',
      '    </div>',
      '  </section>']

io.open('/tmp/index_section.html','w',encoding='utf-8').write("\n".join(L)+"\n")
print('entries:', total, '| linked:', sum(1 for g in GROUPS for r in g[2] if r[2]))
